/******************************************************************************* 
 * Copyright (c) 2014 Red Hat, Inc. 
 * Distributed under license by Red Hat, Inc. All rights reserved. 
 * This program is made available under the terms of the 
 * Eclipse Public License v1.0 which accompanies this distribution, 
 * and is available at http://www.eclipse.org/legal/epl-v10.html 
 * 
 * Contributors: 
 * Red Hat, Inc. - initial API and implementation 
 ******************************************************************************/ 
package org.jboss.tools.jst.web.ui.palette.internal;

import org.jboss.tools.common.model.ui.internal.editors.PaletteItemResult;
import org.jboss.tools.jst.web.ui.internal.editor.jspeditor.JSPTextEditor;
import org.jboss.tools.jst.web.ui.palette.html.wizard.AbstractNewHTMLWidgetWizard;

/**
 * Objects of this class are returned by PaletteManager. and items of Palette.
 * It contains category name, version name, item name,
 * and can compute result generated by wizard with default settings.
 * 
 * @author Viacheslav Kabanovich
 *
 */
public class RunnablePaletteItem {
	String category;
	String version;
	String name;

	public RunnablePaletteItem(String category, String version, String name) {
		this.category = category;
		this.version = version;
		this.name = name;
	}

	/**
	 * 
	 * @return category of palette item
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * 
	 * @return category version of palette item 
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * 
	 * @return name of palette item
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @param textEditor
	 * @return result of generation of palette item wizard with default settings
	 */
	public PaletteItemResult getResult(JSPTextEditor textEditor) {
		return AbstractNewHTMLWidgetWizard.runWithoutUi(textEditor, category, version, name);
	}

}
